server:
  port: ${port.gateway}

logging:
  level:
    org.springframework.boot: 'info'
    org.springframework.cloud: 'info'



hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
#spring:
#  cloud:
#    gateway:
#      routes:


#ribbon:
#  ReadTimeout: 10000
#  ConnectTimeout: 10000


#security:
#  basic:
#    enabled: false
#  oauth2:
##    client:
##      access-token-uri: http://localhost:9004/uaa/oauth/token #令牌端点
##      user-authorization-uri: http://localhost:9004/uaa/oauth/authorize #授权端点
##      client-id: Api-GatWay-Server #OAuth2客户端ID
##      client-secret: secret #OAuth2客户端密钥
#    resource:
#      jwt:
#        key-value: springcloud123 #使用对称加密方式，默认算法d为HS256

#zuul:
#  ignoredServices: '*'
#  routes:
#    auth-service:
#      path: /uaa/**
#      stripPrefix: false
#      sensitiveHeaders:
#    svca-service:
#      path: /svca/**
#      sensitiveHeaders:
#    svcb-service:
#      path: /svcb/**
#      sensitiveHeaders:

#    zuul:
#     routes:
#        yqy-org-perm:
#         path: /yqy-org-perm/**
#         stripPrefix: true
#         url: http://127.0.0.1:81
#    gateway:
#      routes:
#      - id: yqy-org-perm
#        predicates:
#        - Path= /yqy-org-perm/**
#        uri: lb://yqy-org-perm
#        filters:
#        - RewritePath=/yqy-org-perm/(?<path>.*), /$\{path}
#      - id: yiqiyun-web
#        uri: lb://yiqiyun-web
#        predicates:
#        - Path= /web/**
#        filters:
#        - RewritePath=/web/(?<path>.*), /$\{path}
#      - id: web-static
#        uri: lb://yiqiyun-web
#        predicates:
#        - Path= /static/**
#        filters:
#        - RewritePath=/static/(?<path>.*), /$\{path}