server:
  port: ${gateway.port}

logging:
  level:
    org.springframework.boot: 'info'
    org.springframework.cloud: 'info'

spring:
  datasource:
        platform: mysql
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: ${mysql.uri}
        username: ${mysql.username}
        password: ${mysql.password}
        druid:
          validationQuery: SELECT 1
          initialSize: 10
          minIdle: 10
          maxActive: 200
          minEvictableIdleTimeMillis: 180000
          testOnBorrow: false
          testWhileIdle: true
          removeAbandoned: true
          removeAbandonedTimeout: 1800
          logAbandoned: true
          poolPreparedStatements: true
          maxOpenPreparedStatements: 100
          aop-patterns: com.yqy.gateway.dao.*,com.yqy.midend.orgperm.dao.*
  cloud:
    discovery:
      locator:
        enabled: true
#    zuul:
#     routes:
#        yqy-org-perm:
#         path: /yqy-org-perm/**
#         stripPrefix: true
#         url: http://127.0.0.1:81
#    gateway:
#      routes:
#      - id: yqy-org-perm
#        predicates:
#        - Path= /yqy-org-perm/**
#        uri: lb://yqy-org-perm
#        filters:
#        - RewritePath=/yqy-org-perm/(?<path>.*), /$\{path}
#      - id: yiqiyun-web
#        uri: lb://yiqiyun-web
#        predicates:
#        - Path= /web/**
#        filters:
#        - RewritePath=/web/(?<path>.*), /$\{path}
#      - id: web-static
#        uri: lb://yiqiyun-web
#        predicates:
#        - Path= /static/**
#        filters:
#        - RewritePath=/static/(?<path>.*), /$\{path}

zuul:
 host:
  connect-timeout-millis: 10000
  socket-timeout-millis: 60000
 sensitiveHeaders: ""
 routes:


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.yqy.gateway.entities

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000