server:
  port: 9005

logging:
  level:
    org.springframework.boot: 'info'
    org.springframework.cloud: 'info'


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest