server:
  port: ${port:9003}

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${regist.center:http://localhost:9001/eureka}
  instance:
    prefer-ip-address: true

logging:
  level:
    com.netflix.discovery: 'ON'
    org.springframework.cloud: 'info'

spring:
  application:
    name: gateway-service
  datasource:
        platform: mysql
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.50:3306/yqycloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    #    url: jdbc:mysql://101.207.248.146:53306/yqycloud?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: yqy123456
    #    password: root
        druid:
          validationQuery: SELECT 1
          initialSize: 10
          minIdle: 10
          maxActive: 200
          minEvictableIdleTimeMillis: 180000
          testOnBorrow: false
          testWhileIdle: true
          removeAbandoned: true
          removeAbandonedTimeout: 1800
          logAbandoned: true
          poolPreparedStatements: true
          maxOpenPreparedStatements: 100
          aop-patterns: com.yqy.gateway.dao.*,com.yqy.midend.orgperm.dao.*
  cloud:
    discovery:
      locator:
        enabled: true
#    zuul:
#     routes:
#        yqy-org-perm:
#         path: /yqy-org-perm/**
#         stripPrefix: true
#         url: http://127.0.0.1:81
#    gateway:
#      routes:
#      - id: yqy-org-perm
#        predicates:
#        - Path= /yqy-org-perm/**
#        uri: lb://yqy-org-perm
#        filters:
#        - RewritePath=/yqy-org-perm/(?<path>.*), /$\{path}
#      - id: yiqiyun-web
#        uri: lb://yiqiyun-web
#        predicates:
#        - Path= /web/**
#        filters:
#        - RewritePath=/web/(?<path>.*), /$\{path}
#      - id: web-static
#        uri: lb://yiqiyun-web
#        predicates:
#        - Path= /static/**
#        filters:
#        - RewritePath=/static/(?<path>.*), /$\{path}

zuul:
 host:
  connect-timeout-millis: 10000
  socket-timeout-millis: 60000
 sensitiveHeaders: ""
 routes:
    yqy-org-perm:
     path: /yqy-org-perm/**
     stripPrefix: true
     url: http://127.0.0.1:81


mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.yqy.gateway.entities

hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 60000