server:
  port: ${port:8888}

eureka:
  instance:
    hostname: abb
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-Address}:${server.port}
  client:
    enabled: true
#Start Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为。
#    registerWithEureka: false
#    fetchRegistry: false
##end
    serviceUrl:
      defaultZone: ${regist.center:http://loas:loas@localhost:8761/eureka}


# 读取git上面的config数据
spring:
  profiles:
#    active: dev
#  cloud:
#    config:
#      profile: dev
#      server:
#        git:
#          uri: ${git.url:https://github.com/xdcloas113/clouds.git}
#          # ？ 需要真是密码
##          uri: ${git.url:https://github.com/xdcloas113/clouds/tree/master/config-repo}
##          username: ${git.username:xdcloas113@163.com}
##          password: ${git.password:} #需要真实的密码
#          default-label: ${git.label:master}
#          timeout: 30000
#          searchPaths: config-repo  #文件所在的地址必须要  http://localhost:8888/DevConfig-dev.properties
  ##########  读取本地的 ##########
   active: native
  cloud:
    config:
      profile: native
      server:
        native:  #上面都注释掉
          searchLocations:  config-repo  #指定配置文件的位置 访问配置文件 直接 ip:port/文件名字
#          searchLocations:  file:./config-repo/,file:./config-repo/{application},file:./config-repo/{application}/{profile}
#  /{application}/{profile}[/{label}]
#  /{application}-{profile}.yml
#  /{label}/{application}-{profile}.yml
#  /{application}-{profile}.properties
#  /{label}/{application}-{profile}.properties
#  上面的url会映射{application}-{profile}.properties对应的配置文件，{label}对应git上不同的分支，默认为master


encrypt:
    key: loas


logging:
  level:
    com.netflix.discovery: 'ON'
    org.springframework.cloud: 'info'
